configVersion: 2.0

ArenaDac:
    enabled: true
    database: dac
    rated: true
    prefix: "&7[DAC]&e"
    cmd: dac
    joinType: Queue
    victoryCondition: LastManStanding
    nTeams: 2+
    teamSize: 1
    times:
        matchTime: -1
    preReqs: ## Prerequisites for joining
        options: []
    onEnter:
        options: [storeAll]
    onLeave:
        options: [restoreAll]
    onJoin:
        options: []
    onPrestart:
        options: []
    onStart:
        options: [teleportIn, pvpOff, woolTeams, wgNoEnter, wgResetRegion, wgClearRegion]
    onSpawn:
        options: [hunger=20, health=20]
    onDeath:
        options: [respawn, clearInventory]
    onComplete:
        options: [teleportOut, clearInventory]
    winner:
        options: [health=20, hunger=20]
    losers:
        options: []